---

# 0 means auto, and is the default
# 1 means analog
# 2 means HDMI
- name: Analog sound connector
  lineinfile:
    regexp: amixer cset numid=3 ?
    line: amixer cset numid=3 1
    insertbefore: '^exit 0$'
    dest: /etc/rc.local
  notify: play test sound

- name: Fixing audio quality issues
  copy:
    src: asound.conf
    dest: /etc/asound.conf

- name: Install gstreamer0.10-alsa
  apt: name=gstreamer0.10-alsa state=present

- name: alsasink
  ini_file:
    dest: /home/pi/.config/mopidy/mopidy.conf
    section: audio
    option: output
    value: alsasink
    backup: yes
