---

- name: Install mopidy-spotify extension
  apt: name=mopidy-spotify state=latest

- name: Spotify username
  ini_file:
    dest: "{{ mopidy_conf_path }}"
    section: spotify
    option: username
    value: orluke
    backup: yes
  notify: restart mopidy service

- name: Spotify password
  ini_file:
    dest: "{{ mopidy_conf_path }}"
    section: spotify
    option: password
    value: CHANGE ME
    backup: yes
  notify: restart mopidy service
