---
# Note: If things don't quite work right, e.g. MacVim installing without Python
# 2 support, you may need to run:
#   xcode-select --install

- name: Install homebrew
  script: install_homebrew.sh creates=/usr/local/bin/brew

- name: Install MacVim
  homebrew:
    install_options: >
      custom-icons,override-system-vim,with-lua,with-luajit,enable-pythoninterp,with-python-config-dir=/usr/lib/python2.7/config
    name: macvim
    state: latest
    update_homebrew: yes
  register: install_homebrew

- name: Install useful tools
  sudo: no
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - coreutils
    - ctags
    - md5sha1sum
    - ssh-copy-id
    - tree
    - wget
    - watch

- name: Remove tools
  homebrew:
    name: "{{ item }}"
    state: absent
  with_items:
    - git
    - gh

- name: Permissions for /usr/local
  file:
    mode: 0775
    path: /usr/local

- name: Permissions for /Library/Caches/Homebrew
  file:
    mode: 0775
    path: /usr/local
