---
# Note: If things don't quite work right, e.g. MacVim installing without Python
# 2 support, you may need to run:
#   xcode-select --install

- name: Install homebrew
  script: install_homebrew.sh creates=/usr/local/bin/brew

# FIXME: the lineinfile task doesn't work because of permissions
#- name: Install zsh via homebrew
#  homebrew:
#    name: zsh
#    state: latest
#    update_homebrew: yes
#  register: install_homebrew
#
#- name: Non-standard zsh shell
#  lineinfile:
#    dest: /etc/shells
#    line: /usr/local/bin/zsh
#
#- name: Change shell to zsh
#  shell: chsh -s /usr/local/bin/zsh orluke

- name: install oh-my-zsh
  shell: curl -L http://install.ohmyz.sh | sh
  args:
    creates: "~{{ mac_user }}/.oh-my-zsh"

- name: zsh prompt
  lineinfile:
    line: ZSH_THEME="steeef"
    regexp: ZSH_THEME=.*
    dest: "~{{ mac_user }}/.zshrc"

- name: Install MacVim
  homebrew:
    install_options: >
      custom-icons,override-system-vim,with-lua,with-luajit,enable-pythoninterp,with-python-config-dir=/usr/lib/python2.7/config
    name: macvim
    state: latest
    update_homebrew: yes
  register: install_homebrew

- name: Install useful tools
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - ssh-copy-id
    - git
    - gh
