---
## Install Oh-my-zsh
# Edited from: https://github.com/RaymiiOrg/ansible/blob/50ff2d6cb3de2133a312ebcf3501f137ccb31dd5/oh-my-zsh/ohmyzsh.yml

- name: Install git and zsh
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
   - git
   - zsh
   - git-core

- name: Clone oh-my-zsh repo
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /home/{{ zsh_user }}/.oh-my-zsh
    update: no
    accept_hostkey: yes
  register: oh_my_zsh_repo

- name: Set zsh as default shell
  user: name={{ zsh_user }} shell=/bin/zsh

- name: Remove the old version of the file
  file: /home/{{ zsh_user }}/.zshrc
  args:
    state: absent
  when: oh_my_zsh_repo.changed

- name: Recopy the rc file
  shell: cp .oh-my-zsh/templates/zshrc.zsh-template .zshrc
  args:
    creates: .zshrc
    chdir: /home/{{ zsh_user }}
  register: oh_my_zsh_rc

- name: Set the theme
  lineinfile:
    dest: /home/{{ zsh_user }}/.zshrc
    regexp: '^ZSH_THEME=".*"$'
    line: 'ZSH_THEME={{ zsh_theme }}'
    state: present
  when: oh_my_zsh_rc.changed
